name: 'PipeRider Compare Action'

description: 'Run the PipeRider Compare via GitHub Action'

author: 'InfuseAI'

branding:
  icon: 'trending-up'
  color: 'orange'

inputs: 
  github_token: 
    description: 'GITHUB_TOKEN or a personal access token.'
    default: ${{ github.token }}
    required: false
  recipe:
    description: 'The recipe to use for the comparison'
    required: false
  upload:
    description: 'Whether to upload the comparison results to the cloud'
    required: false
  share:
    description: 'Whether to make a share link'
    required: false
  cloud_project:
    description: 'The cloud project to use for the comparison'
    required: false
  cloud_api_token:
    description: 'The API token to use for the cloud API'
    required: false
  credentials_yml:
    description: 'The content of the PipeRider credentials.yml file to use for the PipeRider project'
    required: false

outputs:
  status:
    description: 'The exit code status of the PipeRider comparison. This indicates whether the comparison was successful or not.'
    value: ${{ steps.piperider-compare.outputs.status }}
  uuid:
    description: 'The UUID of the repository that was compared.'
    value: ${{ steps.piperider-compare.outputs.uuid }}

runs:
  using: "composite"
  steps:
    - id: piperider-compare
      uses: ./compare-action
      if: github.event_name == 'pull_request'
      with:
        github_token: ${{ inputs.github_token }}
        recipe: ${{ inputs.recipe }}
        upload: ${{ inputs.upload }}
        share: ${{ inputs.share }}
        cloud_project: ${{ inputs.cloud_project }}
        cloud_api_token: ${{ inputs.cloud_api_token }}
    - name: Upload Generated Report
      uses: actions/upload-artifact@v3
      if: github.event_name == 'pull_request'
      with:
        name: reports
        path: ./report
