name: 'PipeRider Compare Action'

description: 'Run the PipeRider Compare via GitHub Action'

author: 'InfuseAI'

branding:
  icon: 'trending-up'
  color: 'orange'

inputs: 
  github_token: 
    description: 'GITHUB_TOKEN or a personal access token.'
    default: ${{ github.token }}
    required: false
  recipe:
    description: 'The recipe to use for the comparison'
    required: false
  modified:
    description: 'Only compare the modified models'
    default: false
    required: false
  select:
    description: 'Specify the dbt nodes to include'
    required: false
  skip_datasource:
    description: 'Skip accessing the connection of datasource'
    default: false
    required: false
  upload:
    description: 'Whether to upload the comparison results to the cloud'
    required: false
  share:
    description: 'Whether to make a share link'
    required: false
  cloud_project:
    description: 'The cloud project to use for the comparison'
    required: false
  cloud_api_token:
    description: 'The API token to use for the cloud API'
    required: false
  credentials_yml:
    description: 'The content of the PipeRider credentials.yml file to use for the PipeRider project'
    required: false
  working_directory:
    description: 'The working directory to use for the comparison'
    required: false
  piperider_version:
    description: 'The version of PipeRider to use for the comparison'
    required: false

outputs:
  status:
    description: 'The exit code status of the PipeRider comparison. This indicates whether the comparison was successful or not.'
  uuid:
    description: 'The UUID of the repository that was compared.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
