name: 'PipeRider Compare Action'

description: 'Run the PipeRider Compare via GitHub Action'

author: 'InfuseAI'

branding:
  icon: 'trending-up'
  color: 'orange'

inputs: 
  github_token: 
    description: 'GITHUB_TOKEN or a personal access token.'
    default: ${{ github.token }}
    required: false
  recipe:
    description: 'The recipe to use for the comparison'
    required: false
  upload:
    description: 'Whether to upload the comparison results to the cloud'
    required: false
  share:
    description: 'Whether to make a share link'
    required: false
  cloud_project:
    description: 'The cloud project to use for the comparison'
    required: false
  cloud_api_token:
    description: 'The API token to use for the cloud API'
    required: false

outputs:
  status:
    description: 'The exit code status of the PipeRider comparison. This indicates whether the comparison was successful or not.'
  uuid:
    description: 'The UUID of the repository that was compared.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
