#TODO: Change to use piperider/piperider:latest once v0.22.0 officially released
FROM piperider/piperider:0.22.0-alpha.30601

WORKDIR /usr/src/github/
COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
