name: Run tests

on:
  push:
    branches:
      - main
      - feature/action
  pull_request:
    branches:
      - main
      - feature/action


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run action
        uses: ./
        with:
          recipe: <recipe>
          upload: true
          share: true
          cloud_project: <myworkspace/myproject>
          cloud_api_token: <token>