name: Test Action

on:
  push:
    branches:
      - test-action
      - feature/action
  pull_request:
    branches:
      - test-action
      - feature/action


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run compare action
        uses: ./
        env:
          PIPERIDER_API_SERVICE: https://staging.cloud.piperider.io
        with:
          upload: true
          share: false
          cloud_project: TBBT/github-action
          cloud_api_token: ${{ secrets.PIPERIDER_API_TOKEN }}